/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.Quiz;

import java.util.*;
import java.time.*;


public class JPanelQuiz extends JPanel implements QuizInterfaceView, Observer {

    private QuizModel ;

    public QuizModel get() {
        return ;
    }

    public void set(QuizModel ) {
        this. = ;
    }

    public void link(QuizModel _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    @Override

    public void updateView() {

    }

    public void paintComponent() {

    }

    public JPanelQuiz() {

    }

}