/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.Quiz;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+fNPYVc3R3ck= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+fNPYVc3R3ck= >>
// ----------- >>
public class JPanelQuiz extends JPanel implements QuizInterfaceView, Observer {
    // ----------- << attribute.annotations@AAAAAAF+fNYPpM/JJlg= >>
    // ----------- >>
    private QuizModel ;

    public QuizModel get() {
        return ;
    }

    public void set(QuizModel ) {
        this. = ;
    }

    public void link(QuizModel _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    @Override
    // ----------- << method.annotations@AAAAAAF+fML4vs0oDx0= >>
    // ----------- >>
    public void updateView() {
    // ----------- << method.body@AAAAAAF+fML4vs0oDx0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF+fNpVhNKw1t0= >>
    // ----------- >>
    public void paintComponent() {
    // ----------- << method.body@AAAAAAF+fNpVhNKw1t0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF+fNpzt9MWl8g= >>
    // ----------- >>
    public JPanelQuiz() {
    // ----------- << method.body@AAAAAAF+fNpzt9MWl8g= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+fNPYVc3R3ck= >>
// ----------- >>
}