/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.Quiz;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+fNTXcM5oTS8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+fNTXcM5oTS8= >>
// ----------- >>
public interface Observable {
// ----------- << interface.extras@AAAAAAF+fNTXcM5oTS8= >>
// ----------- >>
}