/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.Quiz;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+fNVP986Uj4E= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+fNVP986Uj4E= >>
// ----------- >>
public class QuizController extends JPanel {
    // ----------- << attribute.annotations@AAAAAAF+fN6vN9YwAZU= >>
    // ----------- >>
    private void Attribute1;

    // ----------- << attribute.annotations@AAAAAAF+fN7aB9cCqGA= >>
    // ----------- >>
    private void Attribute2;

    // ----------- << attribute.annotations@AAAAAAF+fN8patjRk48= >>
    // ----------- >>
    private void Attribute3;

    // ----------- << attribute.annotations@AAAAAAF+fNfTytHiQuM= >>
    // ----------- >>
    private QuizModel ;

    public void getAttribute1() {
        return Attribute1;
    }

    public void getAttribute2() {
        return Attribute2;
    }

    public void getAttribute3() {
        return Attribute3;
    }

    public QuizModel get() {
        return ;
    }

    public void setAttribute1(void Attribute1) {
        this.Attribute1 = Attribute1;
    }

    public void setAttribute2(void Attribute2) {
        this.Attribute2 = Attribute2;
    }

    public void setAttribute3(void Attribute3) {
        this.Attribute3 = Attribute3;
    }

    public void set(QuizModel ) {
        this. = ;
    }

    public void link(QuizModel _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF+fN7jQ9dojfw= >>
    // ----------- >>
    public QuizController() {
    // ----------- << method.body@AAAAAAF+fN7jQ9dojfw= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF+fN8EV9gKQrA= >>
    // ----------- >>
    public void actionPerformed() {
    // ----------- << method.body@AAAAAAF+fN8EV9gKQrA= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+fNVP986Uj4E= >>
// ----------- >>
}