/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.Quiz;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+fMVTss1mecs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+fMVTss1mecs= >>
// ----------- >>
public class QuizView extends JPanel implements QuizInterfaceView, Observer {
    // ----------- << attribute.annotations@AAAAAAF+fNBnYM23OaI= >>
    // ----------- >>
    private JLabel _label;

    // ----------- << attribute.annotations@AAAAAAF+fNW6+M7ATxw= >>
    // ----------- >>
    private QuizModel ;

    // ----------- << attribute.annotations@AAAAAAF+fNe2ctGBczM= >>
    // ----------- >>
    private QuizController ;

    public JLabel get_label() {
        return _label;
    }

    public QuizModel get() {
        return ;
    }

    public QuizController get() {
        return ;
    }

    public void set_label(JLabel _label) {
        this._label = _label;
    }

    public void set(QuizModel ) {
        this. = ;
    }

    public void set(QuizController ) {
        this. = ;
    }

    public void link(QuizModel _) {
        set(_);
    }

    public void link(QuizController _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF+fMbOe82VvfY= >>
    // ----------- >>
    public QuizView() {
    // ----------- << method.body@AAAAAAF+fMbOe82VvfY= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAF+fN4Wf9Ucc1c= >>
    // ----------- >>
    public void updateView() {
    // ----------- << method.body@AAAAAAF+fN4Wf9Ucc1c= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+fMVTss1mecs= >>
// ----------- >>
}