/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.Quiz;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+fL/4CMz9mrk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+fL/4CMz9mrk= >>
// ----------- >>
public interface QuizInterfaceView {
    // ----------- << method.annotations@AAAAAAF+fML4vs0oDx0= >>
    // ----------- >>
    void updateView();
// ----------- << interface.extras@AAAAAAF+fL/4CMz9mrk= >>
// ----------- >>
}