/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.Quiz;

import java.util.*;
import java.time.*;


public class QuizView extends JPanel implements QuizInterfaceView, Observer {

    private JLabel _label;


    private QuizModel ;


    private QuizController ;

    public JLabel get_label() {
        return _label;
    }

    public QuizModel get() {
        return ;
    }

    public QuizController get() {
        return ;
    }

    public void set_label(JLabel _label) {
        this._label = _label;
    }

    public void set(QuizModel ) {
        this. = ;
    }

    public void set(QuizController ) {
        this. = ;
    }

    public void link(QuizModel _) {
        set(_);
    }

    public void link(QuizController _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }


    public QuizView() {

    }
    @Override

    public void updateView() {

    }

}